// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQjmxQ3S411sQyvKPZrf1Ti_jcqIHdIcA',
    appId: '1:731582037176:web:d959fcefdad77973af084d',
    messagingSenderId: '731582037176',
    projectId: 'schoolmanagement-17406',
    authDomain: 'schoolmanagement-17406.firebaseapp.com',
    storageBucket: 'schoolmanagement-17406.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_wZXB3mV4asoXEryOSpTfU1RXpJ98odk',
    appId: '1:731582037176:android:8acf12effa1dc429af084d',
    messagingSenderId: '731582037176',
    projectId: 'schoolmanagement-17406',
    storageBucket: 'schoolmanagement-17406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn4hhMzjZk1JCbQKK--rae6REOVJlW_9E',
    appId: '1:731582037176:ios:fb6308e7b6271e26af084d',
    messagingSenderId: '731582037176',
    projectId: 'schoolmanagement-17406',
    storageBucket: 'schoolmanagement-17406.appspot.com',
    iosBundleId: 'com.example.schoolmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn4hhMzjZk1JCbQKK--rae6REOVJlW_9E',
    appId: '1:731582037176:ios:fb6308e7b6271e26af084d',
    messagingSenderId: '731582037176',
    projectId: 'schoolmanagement-17406',
    storageBucket: 'schoolmanagement-17406.appspot.com',
    iosBundleId: 'com.example.schoolmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQjmxQ3S411sQyvKPZrf1Ti_jcqIHdIcA',
    appId: '1:731582037176:web:7fa2f9e04b6f06d4af084d',
    messagingSenderId: '731582037176',
    projectId: 'schoolmanagement-17406',
    authDomain: 'schoolmanagement-17406.firebaseapp.com',
    storageBucket: 'schoolmanagement-17406.appspot.com',
  );
}
